# network parameters
z_dim: 16
f2_dim: 32
stride: 3

# dataloader
train_batch_size: 16
eval_batch_size: 50

# learning process
lr: 0.0001
step_size: 32
gamma: 0.6
num_epoch_vae: 200
num_epoch_sampler: 50
