# network parameters
z_dim: 16
f2_dim: 32
stride: 3

# dataloader
train_batch_size: 16
eval_batch_size: 100

# learning process
lr: 0.0008
step_size: 32
gamma: 0.9
num_epoch_vae: 500
num_epoch_sampler: 200